services:
  track1_segment-1-1:
    environment:
      KAFKA_BROKER: kafka:9092
      NEXT_SEGMENT: segment-2-2
      SEGMENT_ID: segment-1-1
      SEGMENT_TYPE: normal
      TRACK_ID: '1'
    image: segment-image
    restart: always
  track1_segment-1-2:
    environment:
      KAFKA_BROKER: kafka:9092
      NEXT_SEGMENT: segment-1-3
      SEGMENT_ID: segment-1-2
      SEGMENT_TYPE: blocked
      TRACK_ID: '1'
    image: segment-image
    restart: always
  track1_segment-1-3:
    environment:
      KAFKA_BROKER: kafka:9092
      NEXT_SEGMENT: start-and-goal-1
      SEGMENT_ID: segment-1-3
      SEGMENT_TYPE: normal
      TRACK_ID: '1'
    image: segment-image
    restart: always
  track1_start-and-goal-1:
    environment:
      KAFKA_BROKER: kafka:9092
      NEXT_SEGMENT: segment-1-1
      SEGMENT_ID: start-and-goal-1
      SEGMENT_TYPE: start-goal
      TRACK_ID: '1'
    image: segment-image
    restart: always
  track2_segment-2-1:
    environment:
      KAFKA_BROKER: kafka:9092
      NEXT_SEGMENT: segment-2-2
      SEGMENT_ID: segment-2-1
      SEGMENT_TYPE: normal
      TRACK_ID: '2'
    image: segment-image
    restart: always
  track2_segment-2-2:
    environment:
      KAFKA_BROKER: kafka:9092
      NEXT_SEGMENT: segment-1-3
      SEGMENT_ID: segment-2-2
      SEGMENT_TYPE: normal
      TRACK_ID: '2'
    image: segment-image
    restart: always
  track2_segment-2-3:
    environment:
      KAFKA_BROKER: kafka:9092
      NEXT_SEGMENT: start-and-goal-2
      SEGMENT_ID: segment-2-3
      SEGMENT_TYPE: blocked
      TRACK_ID: '2'
    image: segment-image
    restart: always
  track2_start-and-goal-2:
    environment:
      KAFKA_BROKER: kafka:9092
      NEXT_SEGMENT: segment-2-1
      SEGMENT_ID: start-and-goal-2
      SEGMENT_TYPE: start-goal
      TRACK_ID: '2'
    image: segment-image
    restart: always
version: '3'
